s = set() # creating an empty set
n = input("Enter a number: ")
s.add(n)
n = input("Enter a number: ")
s.add(n)
n = input("Enter a number: ")
s.add(n)
n = input("Enter a number: ")
s.add(n)
n = input("Enter a number: ")
s.add(n)
n = input("Enter a number: ")
s.add(n)
n = input("Enter a number: ")
s.add(n)
n = input("Enter a number: ")
s.add(n)

print(s)